modLoader="javafml"
loaderVersion="[36,)"
license=" Public Domain"
[[mods]]
modId="falldamagetweak"
version="${version}"
displayName="Fall Damage Tweak"
authors="FionaTheMortal"
description="    Fall Damage Tweak is a Forge mod that makes fall damage depend on the entity's speed."

[[dependencies.falldamagetweak]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.falldamagetweak]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
